---
- name: Install Docker with all components
  yum:
    name:
      - docker
      - containerd ุง
    state: present
    update_cache: yes  
  become: yes   

- name: Start and enable Docker service
  service:
    name: docker
    state: started 
    enabled: yes   
  become: yes

- name: Add user to docker group
  user:
    name: ec2-user  
    groups: docker
    append: yes  
  become: yes
